name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

defaults:
  run:
    working-directory: ./src/Tunnel2.LoadTests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      # Note: Tests are not run automatically
      # Load tests should be run manually or on a schedule
      # See LOAD_TESTING_ROADMAP.md for implementation plan
